# Generated by Django 5.0 on 2023-12-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dueño',
            new_name='Dueno',
        ),
        migrations.RenameField(
            model_name='dueno',
            old_name='id_dueño',
            new_name='id_dueno',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='dueños',
            new_name='duenos',
        ),
    ]
